title: Tune MTB
email: nscipione+danylson@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Mountain Bike Service and Suspension. Rochester, NY.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danylson-dev.github.io/tune-mtb" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: minima
plugins:
  - jekyll-feed

# Navigation links
navigation:
  - title: Home
    url: /
  - title: Services
    url: /services/
  - title: History
    url: /history/
  - title: Contact
    url: /contact/

relative_permalinks: false